[0m[[0m[31merror[0m] [0m[0m/mnt/c/Users/pdcdi/Documents/Scala/tasky/src/main/scala/taskmanager.scala:3:91: not found: value LocalDate[0m
[0m[[0m[31merror[0m] [0m[0m  def allTasksDueToday(tasks: List[Task]): List[Task] = tasks.filter(t => t.dueOn.isEqual(LocalDate.now))[0m
[0m[[0m[31merror[0m] [0m[0m                                                                                          ^[0m
[0m[[0m[31merror[0m] [0m[0mone error found[0m
